### ISSUE TITLE
link to object? is broken

### ISSUE THREAD

**Issue by tiye** [oakmac/cljs-cheatsheet#13]
https://clojuredocs.org/clojure.core/object_q got 404

**Comment by puredanger** [comment]
Note that this function doesn't exist in Clojure. Presumably should go to http://cljs.github.io/api/cljs.core/#objectQMARK

**Comment by oakmac** [comment]
Ah - `object?` does not exist in Clojure.

I need to give this a think; might be better for the cheatsheet to link to http://cljs.github.io/api/ these days.

Thanks for the report!
