### ISSUE TITLE
Release the latest version to fix docs for filter

### ISSUE THREAD

**Issue by holyjak** [oakmac/cljs-cheatsheet#23]
https://github.com/oakmac/cljs-cheatsheet/commit/3b76cdc6dc491a2174bc11dac1cabe47374db2f7 has fixed the tooltip doc for filter in April yet http://cljs.info/cheatsheet/ still shows the old, wrong one. Can this be released? Thank you!

**Comment by oakmac** [comment]
Updated 👍 

Sorry this took so long.

**Comment by holyjak** [comment]
Awesome, thanks!
