### ISSUE TITLE
missing array-seq 

### ISSUE THREAD

**Issue by phiat** [oakmac/cljs-cheatsheet#28]
array-seq is missing in the html.   Where should this be added?   js interop  section? or create seq section?

**Comment by oakmac** [comment]
Thank you for this suggestion! I think under the "create a seq" section is most appropriate.

Fixed with [Commit #dc4349a5](https://github.com/oakmac/cljs-cheatsheet/commit/dc4349a59b5d16ad6d225bb3d3163c26f6ec5af8)
