### ISSUE TITLE
tooltips should "flip up" when at the bottom

### ISSUE THREAD

**Issue by oakmac** [oakmac/cljs-cheatsheet#3]
Tooltip content should always display on the visible screen.

Right now if you hover over a tooltip near the bottom of the page, the tooltip body will show below the visible screen. In this instance, it should "flip up" and display above where the mouse cursor is.

@lesleymdcampo - You worked with the left/right positioning when a tooltip is at the edge of the screen. Want to take a look at this one?

**Comment by LesleyMdCampo** [comment]
i will take a look
