### ISSUE TITLE
Use this 'template' for Clojure Cheatsheet too?

### ISSUE THREAD

**Issue by aadrian** [oakmac/cljs-cheatsheet#36]
Hi,

This cheatsheet for ClojureScript is very usable and readable :smiley:  .

Would it be possible to apply this "template" for the Clojure cheatsheet to?

Thank you.

**Comment by oakmac** [comment]
> This cheatsheet for ClojureScript is very usable and readable

Thank you for the kind words! I'm glad you enjoy the design.

> Would it be possible to apply this "template" for the Clojure cheatsheet too?

It is certainly possible, although I do not have access to make changes on the clojure.org domain (ie: I do not run that website).

The code for the CLJS cheatsheet is licensed under the permissive MIT license, so it may be freely extended by anyone :)
