### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by roman01la** [oakmac/cljs-cheatsheet#6]
Hello and thank you for http://cljs.info/cheatsheet/! It's very helpful piece. I'm building a website for ClojureScript learning resources in russian. Do you mind if I use information from your website as a base for russian translation?

**Comment by oakmac** [comment]
> Do you mind if I use information from your website as a base for a Russian translation?

Not at all! Please feel free to use the information however you wish :)

Let me know if you decide to build a Russian clone of the cheatsheet and I will link to it from the main site.

**Comment by roman01la** [comment]
Thanks! I'll let you know!
